name: Deploy to Heroku (Board service)

on:
  push:
    branches:
      - main
    paths:
      - "board_service/**"
      - ".github/workflows/boardservice.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add board service remote origin
        run: git remote add heroku-boardservice https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BOARDSERVICE_URI }}.git
      - name: Deploy board service to heroku
        run: git push heroku-boardservice `git subtree split --prefix board_service main`:refs/heads/main --force
