name: Deploy to Heroku (Chat Service)

on:
  push:
    branches:
      - main
    paths:
      - "chat_service/**"
      - ".github/workflows/chatservice.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add chat service remote origin
        run: git remote add heroku-chatservice https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_CHATSERVICE_URI }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-chatservice `git subtree split --prefix chat_service main`:refs/heads/main --force
