name: Deploy to Heroku (Meet)

on:
  push:
    branches:
      - main
    paths:
      - "meet/**"
      - ".github/workflows/meet.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add meet to remote origin
        run: git remote add heroku-meet https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_MEET_URI }}.git
      - name: Deploy meet to heroku
        run: git push heroku-meet `git subtree split --prefix meet main`:refs/heads/main --force