name: Deploy to Heroku (Project Service)

on:
  push:
    branches:
      - main
    paths:
      - "project_service/**"
      - ".github/workflows/projectservice.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add project service remote origin
        run: git remote add heroku-projectservice https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_PROJECTSERVICE_URI }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-projectservice `git subtree split --prefix project_service main`:refs/heads/main --force
