name: Deploy to Heroku (User service)

on:
  push:
    branches:
      - main
    paths:
      - "user_service/**"
      - ".github/workflows/userservice.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add user service remote origin
        run: git remote add heroku-userservice https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_USERSERVICE_URI }}.git
      - name: Deploy user service to Heroku
        run: git push heroku-userservice `git subtree split --prefix user_service main`:refs/heads/main --force